# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from . import service_pb2 as v1_dot_query_dot_service__pb2

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in v1/query/service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class QueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
            "/v1.query.QueryService/ExecuteQuery",
            request_serializer=v1_dot_query_dot_service__pb2.ExecuteQueryRequest.SerializeToString,
            response_deserializer=v1_dot_query_dot_service__pb2.ExecuteQueryResponse.FromString,
            _registered_method=True,
        )
        self.ValidateQuery = channel.unary_unary(
            "/v1.query.QueryService/ValidateQuery",
            request_serializer=v1_dot_query_dot_service__pb2.ValidateQueryRequest.SerializeToString,
            response_deserializer=v1_dot_query_dot_service__pb2.ValidationResponse.FromString,
            _registered_method=True,
        )


class QueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteQuery": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteQuery,
            request_deserializer=v1_dot_query_dot_service__pb2.ExecuteQueryRequest.FromString,
            response_serializer=v1_dot_query_dot_service__pb2.ExecuteQueryResponse.SerializeToString,
        ),
        "ValidateQuery": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateQuery,
            request_deserializer=v1_dot_query_dot_service__pb2.ValidateQueryRequest.FromString,
            response_serializer=v1_dot_query_dot_service__pb2.ValidationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "v1.query.QueryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("v1.query.QueryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteQuery(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/v1.query.QueryService/ExecuteQuery",
            v1_dot_query_dot_service__pb2.ExecuteQueryRequest.SerializeToString,
            v1_dot_query_dot_service__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateQuery(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/v1.query.QueryService/ValidateQuery",
            v1_dot_query_dot_service__pb2.ValidateQueryRequest.SerializeToString,
            v1_dot_query_dot_service__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
