# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/query/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "v1/query/service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16v1/query/service.proto\x12\x08v1.query"c\n\x13\x45xecuteQueryRequest\x12\x15\n\rdb_identifier\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05"y\n\x14\x45xecuteQueryResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x11\n\trow_count\x18\x02 \x01(\x05\x12\x14\n\x0c\x65xecution_ms\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t"<\n\x14ValidateQueryRequest\x12\x15\n\rdb_identifier\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t":\n\x12ValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xac\x01\n\x0cQueryService\x12M\n\x0c\x45xecuteQuery\x12\x1d.v1.query.ExecuteQueryRequest\x1a\x1e.v1.query.ExecuteQueryResponse\x12M\n\rValidateQuery\x12\x1e.v1.query.ValidateQueryRequest\x1a\x1c.v1.query.ValidationResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.query.service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EXECUTEQUERYREQUEST"]._serialized_start = 36
    _globals["_EXECUTEQUERYREQUEST"]._serialized_end = 135
    _globals["_EXECUTEQUERYRESPONSE"]._serialized_start = 137
    _globals["_EXECUTEQUERYRESPONSE"]._serialized_end = 258
    _globals["_VALIDATEQUERYREQUEST"]._serialized_start = 260
    _globals["_VALIDATEQUERYREQUEST"]._serialized_end = 320
    _globals["_VALIDATIONRESPONSE"]._serialized_start = 322
    _globals["_VALIDATIONRESPONSE"]._serialized_end = 380
    _globals["_QUERYSERVICE"]._serialized_start = 383
    _globals["_QUERYSERVICE"]._serialized_end = 555
# @@protoc_insertion_point(module_scope)
